Allow writer user to create tables in schema
movetokube/postgres-operator pull request #136
Opened 2023-10-26 09:32 UTC by mfuhrmeisterDM

# why
In postgres 15 they change the behaviour of the public schema. Now only the owner can create tables in this schema. And the user is in charge to configure the permissions.

# proposed change
Grant the writer user to also create tables in a schema.

# usage
add the public schema explicitly to the list of schemas to create, to force the schema privileges to be applied.

2023-11-13 14:13 UTC, hitman99 requested changes

2023-11-13 14:13 UTC, hitman99 commented on pkg/postgres/database.go
> +
Why not add this to `SetSchemaPrivileges` instead of creating an additional function?

2023-12-04 15:23 UTC, mfuhrmeisterDM commented on pkg/postgres/database.go
> +
`SetSchemaPrivileges` is also called for the reader, so I would need to change the signature to indicate if the create privilege must be granted or not. 
I would think this should not be enabled for the reader.
I will rework this tomorrow.

2024-02-13 07:33 UTC, pcallewaert commented
👋 We tested this PR out as we are migrating to PG15, but we noticed this was only a part of the solution. We also had to call the new function for the `public` schema in the db creation logic when the ownership is transferred to the new owner, and also for the writer group.

@mfuhrmeisterDM are you still working on this? If not, I can try to work on this.

2024-02-13 13:58 UTC, mfuhrmeisterDM commented on pkg/postgres/database.go
> +
@hitman99 I updated the code, is this more what you had in mind?

2024-02-13 13:59 UTC, mfuhrmeisterDM commented
@pcallewaert I updated the PR like requested. I must say I almost forgot this PR, thanks for the reminder.

2024-02-13 14:00 UTC, mfuhrmeisterDM commented
> 👋 We tested this PR out as we are migrating to PG15, but we noticed this was only a part of the solution. We also had to call the new function for the `public` schema in the db creation logic when the ownership is transferred to the new owner, and also for the writer group.

Can you explain a bit more what you mean, because in our case this worked fine.

2024-02-14 07:53 UTC, pcallewaert commented
> > 👋 We tested this PR out as we are migrating to PG15, but we noticed this was only a part of the solution. We also had to call the new function for the `public` schema in the db creation logic when the ownership is transferred to the new owner, and also for the writer group.
> 
> Can you explain a bit more what you mean, because in our case this worked fine.

Of course. We are using a very basic `Postgres` resource:

```yaml
apiVersion: db.movetokube.com/v1alpha1
kind: Postgres
metadata:
  name: postgresdb
spec:
  database: example-db
  dropOnDelete: true
  extensions:
    - fuzzystrmatch
```

We don't have `schemas` defined as we just use the `public` schema, and we use the owner permissions for our user.
The code changes here are made in the for loop for each schema. So we never hit the new code as this is an empty array.
In our patched version we re-used your method on L180 during the database creation logic, but specific for the `public` schema for the owner group.

2024-02-14 10:08 UTC, mfuhrmeisterDM commented
> r hit the new code as t

got it, will address this.

2024-02-14 10:09 UTC, mfuhrmeisterDM commented
> Of course. We are using a very basic `Postgres` resource:
> 
> ```yaml
> apiVersion: db.movetokube.com/v1alpha1
> kind: Postgres
> metadata:
>   name: postgresdb
> spec:
>   database: example-db
>   dropOnDelete: true
>   extensions:
>     - fuzzystrmatch
> ```
> 
> We don't have `schemas` defined as we just use the `public` schema, and we use the owner permissions for our user. The code changes here are made in the for loop for each schema. So we never hit the new code as this is an empty array. In our patched version we re-used your method on L180 during the database creation logic, but specific for the `public` schema for the owner group.

Got it, I will address this.

2024-02-14 18:45 UTC, pcallewaert commented
> > Of course. We are using a very basic `Postgres` resource:
> > ```yaml
> > apiVersion: db.movetokube.com/v1alpha1
> > kind: Postgres
> > metadata:
> >   name: postgresdb
> > spec:
> >   database: example-db
> >   dropOnDelete: true
> >   extensions:
> >     - fuzzystrmatch
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > We don't have `schemas` defined as we just use the `public` schema, and we use the owner permissions for our user. The code changes here are made in the for loop for each schema. So we never hit the new code as this is an empty array. In our patched version we re-used your method on L180 during the database creation logic, but specific for the `public` schema for the owner group.
> 
> Got it, I will address this. Edit: I double checked our code and we had the same problem. But we instead just added the public schema to the list of schemes. Is this also an option to you? (@pcallewaert )

If it works it is certainly an option :D I'll have to test it out, I'm hoping to do it this week.

2024-02-21 08:28 UTC, mfuhrmeisterDM commented
@hitman99 can you please have a look?

2024-02-21 16:02 UTC, hitman99 commented
Nice work, will check this out tomorrow. If there's no problems this will be merged and released as well

2024-02-22 12:04 UTC, pcallewaert commented
👋 I've finally found time to test it out, and the PR should indeed work for the writer user specific. But for the OWNER privilege it is missing a bit.
During the CreateDB we should also give the owner group the permissions to create in the database. Even as owner, you don't have the permissions to create without the explicit `GRANT`.
https://github.com/pcallewaert/postgres-operator/blob/pc/test-pg15-fix/pkg/postgres/database.go#L45-L53

2024-02-25 10:49 UTC, hitman99 requested changes

2024-02-25 10:49 UTC, hitman99 commented on pkg/controller/postgres/postgres_controller.go
> +		err = r.pg.SetSchemaPrivileges(database, owner, reader, schema, readerPrivs, false, reqLogger)
I think it's time to introduce option struct instead of passing 7 arguments to a function.

2024-02-25 10:49 UTC, hitman99 commented on pkg/controller/postgres/postgres_controller.go
> +		err = r.pg.SetSchemaPrivileges(database, owner, writer, schema, writerPrivs, true, reqLogger)
Same as above comment

2024-02-26 15:28 UTC, mfuhrmeisterDM commented on pkg/controller/postgres/postgres_controller.go
> +		err = r.pg.SetSchemaPrivileges(database, owner, writer, schema, writerPrivs, true, reqLogger)
will do this in the next days

2024-02-27 13:53 UTC, mfuhrmeisterDM commented on pkg/controller/postgres/postgres_controller.go
> +		err = r.pg.SetSchemaPrivileges(database, owner, reader, schema, readerPrivs, false, reqLogger)
done

2024-02-27 13:53 UTC, mfuhrmeisterDM commented
> 👋 I've finally found time to test it out, and the PR should indeed work for the writer user specific. But for the OWNER privilege it is missing a bit. During the CreateDB we should also give the owner group the permissions to create in the database. Even as owner, you don't have the permissions to create without the explicit `GRANT`. https://github.com/pcallewaert/postgres-operator/blob/pc/test-pg15-fix/pkg/postgres/database.go#L45-L53

incorporated this

2024-02-28 13:24 UTC, hitman99 approved these changes

2024-02-28 13:27 UTC, hitman99 commented
Hey @mfuhrmeisterDM woud you mind merging master or rebasing on master? I approve the changes but would like to base it on master. Once that's done I'll merge & release it

2024-02-29 10:48 UTC, merged