Add support for template secrets
movetokube/postgres-operator pull request #143
Opened 2023-12-13 15:33 UTC by reddec

Add support for template secrets.

Users can specify the structure and content of secrets based on their unique requirements using standard 
[Go templates](https://pkg.go.dev/text/template#hdr-Actions). This flexibility allows for a more tailored approach to
meeting the specific needs of different applications.

Available context:

| Variable    | Meaning                  |
|-------------|--------------------------|
| `.Host`     | Database host            |
| `.Role`     | Generated user/role name |
| `.Database` | Referenced database name |
| `.Password` | Generated role password  |

Example

```yaml
apiVersion: db.movetokube.com/v1alpha1
kind: PostgresUser
metadata:
  name: my-db-user
spec:
  role: username
  database: my-db
  secretName: my-secret
  privileges: OWNER
  template:
    PQ_URL: "host={{.Host}} user={{.Role}} password={{.Password}} dbname={{.Database}}"
```

Change is backward compatible: no need to update existing CRDs in cluster.

2023-12-13 15:34 UTC, reddec commented
@hitman99 sorry for bothering you, but could you please review one more PR?

2023-12-19 11:37 UTC, hitman99 commented on README.md
> +  template:             # Output secrets can be customized using standard Go templates
I think that `template` is a bit misleading, would it be possible to change it to `secretTemplate` or something else that indicates that this fiel is used to template data in the secret

2023-12-19 11:40 UTC, hitman99 requested changes
I think it's a bit misleading to name that field `template`. From the name itself it's not clear that it is allowing to template the data in the secret

2023-12-19 16:59 UTC, reddec commented
@hitman99 updated

2023-12-20 16:09 UTC, hitman99 approved these changes

2023-12-20 16:09 UTC, merged