GCP wrapper
movetokube/postgres-operator pull request #83
Opened 2022-03-31 15:53 UTC by aroundthecode

Add a GCP wrapper to work on Google SQL instances

In reference to #82 and #63 I tried to provide an initial GCP implementation.

To have operator work with GCP you have 
1) use postgres connection in secret
2) manually create a Master role e.g. "devops-operators" (must NOT be the same as the connection secret)
3) use such role in database CR e.g. spec.masterRole: devops-operator

DropRole method will check for db owner and will skip master role dropping.

I'm not a GO developer so I tried to keep all modification in gcp.go, please modify at will to make it compliant with other code style 

Working with both Database and Role CR, both in creation and deletion.
@hitman99

2022-04-01 10:59 UTC, hitman99 commented
Thank you for your contribution, I will get this reviewed today

2022-04-01 13:19 UTC, hitman99 requested changes

2022-04-01 13:19 UTC, hitman99 commented on pkg/postgres/gcp.go
> +To have operator work with GCP you have
Would you mind adding these to the README.md so people would not have to dig in code comments ?

2022-04-01 13:19 UTC, hitman99 commented on pkg/postgres/gcp.go
> +
remove empty line

2022-04-01 13:19 UTC, hitman99 commented on pkg/postgres/gcp.go
> +	q := fmt.Sprintf("SELECT pg_catalog.pg_get_userbyid(d.datdba) FROM pg_catalog.pg_database d WHERE d.datname = '%s';", database)
This should be in postgres.go and not hardcoded here

2022-04-01 13:19 UTC, hitman99 commented on pkg/postgres/gcp.go
> +
remove empty line

2022-04-01 13:19 UTC, hitman99 commented on pkg/postgres/gcp.go
> +
remove empty line

2022-04-05 07:59 UTC, aroundthecode commented
@hitman99 any chance you can review this shortly and generate a new version?
I'm using a patched operator version, but I'd prefer to stay on the mainstream :)

2022-04-06 07:47 UTC, hitman99 approved these changes

2022-04-06 07:49 UTC, hitman99 commented
@aroundthecode PR approved and merged. Thanks for using my operator :)

2022-04-06 07:49 UTC, merged