Add helm chart for the operator installation
movetokube/postgres-operator pull request #90
Opened 2022-05-18 10:55 UTC by samm-git

This PR is to add helm chart for the Postgres Operator installation. I think it could be more convenient compared to k8s kustomize way for many usecases. Please let me know if you want any changes or parameters to be added.

## Changes in the PR:

- Helm added
- Added CI action to host helm using github pages

2022-05-18 10:57 UTC, samm-git commented
P.S. Its also possible to host chart on the github pages itself. I can add this to this or next PR.

2022-08-29 13:07 UTC, hitman99 requested changes

2022-08-29 13:07 UTC, hitman99 commented on charts/ext-postgres-operator/templates/operator.yaml
> +              value: ""
Could you add this to values.yaml please? In case someone wants to watch specific namespace.

2022-10-29 10:02 UTC, hitman99 approved these changes

2022-10-29 10:07 UTC, merged